[package]
name = "sayler"
version = "0.1.0"
authors = ["Kirby Linvill <kjlinvill@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
rayon = "1.4.0"
structopt = "0.3.18"